"""created Car table

Revision ID: 51060ec8b55b
Revises: 7da6025ad894
Create Date: 2021-11-10 16:54:55.806808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51060ec8b55b'
down_revision = '7da6025ad894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('year', sa.String(length=50), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
